artifact_uri: file:///home/aamir/mlops/stores/model/1/370dcb9e699e433b92d69e428b1784f1/artifacts
end_time: 1668450223300
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 370dcb9e699e433b92d69e428b1784f1
run_uuid: 370dcb9e699e433b92d69e428b1784f1
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450223268
status: 3
tags: []
user_id: aamir
