artifact_uri: file:///home/aamir/mlops/stores/model/1/d1b20d70a5c04e87b834b618cb848f47/artifacts
end_time: 1668450218489
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: d1b20d70a5c04e87b834b618cb848f47
run_uuid: d1b20d70a5c04e87b834b618cb848f47
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450218461
status: 3
tags: []
user_id: aamir
