artifact_uri: file:///home/aamir/mlops/stores/model/1/b1544e34aa804a51a822b07e4f03ee50/artifacts
end_time: 1668450246425
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: b1544e34aa804a51a822b07e4f03ee50
run_uuid: b1544e34aa804a51a822b07e4f03ee50
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450246405
status: 3
tags: []
user_id: aamir
