artifact_uri: file:///home/aamir/mlops/stores/model/1/353a14699f5a4b849d78ca2b2782ecff/artifacts
end_time: 1668450258787
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 353a14699f5a4b849d78ca2b2782ecff
run_uuid: 353a14699f5a4b849d78ca2b2782ecff
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450258764
status: 3
tags: []
user_id: aamir
