artifact_uri: file:///home/aamir/mlops/stores/model/0/dfc7634a1c994b808d6d4c9839be6b44/artifacts
end_time: 1668860615939
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dfc7634a1c994b808d6d4c9839be6b44
run_uuid: dfc7634a1c994b808d6d4c9839be6b44
source_name: ''
source_type: 4
source_version: ''
start_time: 1668860609260
status: 3
tags: []
user_id: aamir
