artifact_uri: file:///home/aamir/mlops/stores/model/1/7e1bc94c7c07408a9a7b28102fc43046/artifacts
end_time: 1668450277071
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 7e1bc94c7c07408a9a7b28102fc43046
run_uuid: 7e1bc94c7c07408a9a7b28102fc43046
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450277043
status: 3
tags: []
user_id: aamir
