artifact_uri: file:///home/aamir/mlops/stores/model/1/e4dbb0deb8c04b04a1697fbea897ed67/artifacts
end_time: 1668450266917
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: e4dbb0deb8c04b04a1697fbea897ed67
run_uuid: e4dbb0deb8c04b04a1697fbea897ed67
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450266885
status: 3
tags: []
user_id: aamir
