artifact_uri: file:///home/aamir/mlops/stores/model/1/71ce4b391c1a40bc83be49f56fd0ed1d/artifacts
end_time: 1668450238449
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 71ce4b391c1a40bc83be49f56fd0ed1d
run_uuid: 71ce4b391c1a40bc83be49f56fd0ed1d
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450238435
status: 3
tags: []
user_id: aamir
