artifact_uri: file:///home/aamir/mlops/stores/model/1/0df76e03d66245028f396acb0a9d2c84/artifacts
end_time: 1668450284724
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 0df76e03d66245028f396acb0a9d2c84
run_uuid: 0df76e03d66245028f396acb0a9d2c84
source_name: ''
source_type: 4
source_version: ''
start_time: 1668450284702
status: 3
tags: []
user_id: aamir
